# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b38947472e950bf254d7facd758f21cdbcf509ec394e376e260593d8aa7e87a5c16f5ec490a4e3175b2e21d7cd88baae89dd145967552889451e7a93a3b48f0b

test:
  secret_key_base: 0ae01e796e60f89668c2cdfc4ba0bf864d7916da1e3a67f363e6d2c2e655ff8a7a54a0408fcd72c751018f7a99b1b7fe2681aa12111857b5160f8e317e8ef784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
